### ISSUE TITLE
accounts tab always visible

### ISSUE THREAD

**Issue by BennHi** [Project60/org.project60.banking#411]
When I set the menu position of the accounts tab in the settings to not show or show in the contributions tab, this doesn't seem to change anything. The tab is still visible which is especially problematic with users who shall have no business in contributions whatsoever. 

On a sidenote: I also noticed, that the tab doesn't show in the "Contact Summary Editor" Extension. Maybe this helps tracking down the issue.

**Comment by eptbertram** [comment]
The tab shows in my "Contact Layout Editor" (v 2.2.2) and is editable & able to hide. 

CiviCRM 5.67.0 with Drupal 10.2.2 or WordPress 6.4.2. What is your CMS and version, @BennHi ?

**Comment by BennHi** [comment]
I am using "org.project60.banking" v0.8.3 with "Contact Layout Editor" v2.2.2 in CiviCRM 5.69.0 with WordPress 6.4.2.

<img width="1235" alt="Bildschirmfoto 2024-01-30 um 17 05 49" src="https://github.com/Project60/org.project60.banking/assets/57151596/fd9529fd-fbe6-40f0-8c1a-50ab60a3c679">
<img width="1237" alt="Bildschirmfoto 2024-01-30 um 17 05 31" src="https://github.com/Project60/org.project60.banking/assets/57151596/2e2e4b07-2908-4a5b-865d-154eab67ddb5">

**Comment by eptbertram** [comment]
Your versions are good :) A big difference: I installed the theme The Island, an extension from https://lab.civicrm.org/extensions/theisland/ Maybe you like to give it a try? After installation it needs to be configured via admin-menu > display settings > display preferences. Maybe your error is solved with this new template? 

I noticed in my Drupal 10 install that the tab for Relationships has gone after upgrading to 5,69.x. This is very strange, too. Maybe your issue isn't from banking extension, but a tab-related problem?

**Comment by BennHi** [comment]
Hmm.. yes maybe it's a tab related issue. I'll try installing the theme in a minute but in the mean time here is the view of the display preferences (if I translated to german correctly). There seems to be no option for Accounts (ger. Konten) visible.
<img width="531" alt="image" src="https://github.com/Project60/org.project60.banking/assets/57151596/d0474a84-347f-4349-a760-7611ede756c7">

**Comment by BennHi** [comment]
I see, thanks for explaining. I just installed The Island and it looks great but the tab issue persists.
<img width="439" alt="Bildschirmfoto 2024-01-30 um 18 04 12" src="https://github.com/Project60/org.project60.banking/assets/57151596/9c817fd7-e1ad-49c3-9a36-14d0ff779dfd">

**Comment by eptbertram** [comment]
I guess there are no permissions for CiviBanking. 
Sorry that I couldn't help further.

**Comment by jensschuppe** [comment]
> When I set the menu position of the accounts tab in the settings to not show or show in the contributions tab, this doesn't seem to change anything. The tab is still visible

This option isn't about the *Accounts* tab but the *CiviBanking* submenu within the navigation menu. The *Accounts* tab currently can not be hidden:
https://github.com/Project60/org.project60.banking/blob/71738e3e6d78f38756574fc8f1f30c4930086b5c/banking.php#L166-L183

As this code also checks for a contact ID as context, the tab isn't available to the *Contact Layout Editor*. This should be adjusted. Also, a permission would be useful - as being done [here](https://github.com/systopia/de.systopia.donrec/blob/d1b455440fc5f93b2d5f0ecf6b8975968cb82a7b/donrec.php#L277-L298).

Would any of you be able to provide a PR for this?

**Comment by BennHi** [comment]
I am currently only running one in production instance and I am afraid to mess it up as I am still pretty new to civi. 
Also I updated to using smarty v3 today and thus deactivated the banking extension for now. Fun fact: The tab is still there ;) But it throws an error and doesn't load any content.
